# Form implementation generated from reading ui file 'proj2.ui'
#
# Created by: PyQt6 UI code generator 6.11.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_startscr(object):
    def setupUi(self, startscr):
        startscr.setObjectName("startscr")
        startscr.resize(750, 550)
        startscr.setMinimumSize(QtCore.QSize(750, 550))
        startscr.setMaximumSize(QtCore.QSize(750, 550))
        self.centralwidget = QtWidgets.QWidget(parent=startscr)
        self.centralwidget.setObjectName("centralwidget")
        self.gamename = QtWidgets.QLabel(parent=self.centralwidget)
        self.gamename.setGeometry(QtCore.QRect(340, 50, 81, 121))
        font = QtGui.QFont()
        font.setFamily("Impact")
        font.setPointSize(36)
        self.gamename.setFont(font)
        self.gamename.setObjectName("gamename")
        self.start = QtWidgets.QPushButton(parent=self.centralwidget)
        self.start.setGeometry(QtCore.QRect(325, 360, 100, 40))
        font = QtGui.QFont()
        font.setFamily("Imprint MT Shadow")
        font.setPointSize(12)
        self.start.setFont(font)
        self.start.setObjectName("start")
        self.doub = QtWidgets.QRadioButton(parent=self.centralwidget)
        self.doub.setGeometry(QtCore.QRect(430, 300, 101, 20))
        font = QtGui.QFont()
        font.setFamily("Comic Sans MS")
        self.doub.setFont(font)
        self.doub.setObjectName("doub")
        self.single = QtWidgets.QRadioButton(parent=self.centralwidget)
        self.single.setGeometry(QtCore.QRect(250, 300, 100, 20))
        font = QtGui.QFont()
        font.setFamily("Comic Sans MS")
        self.single.setFont(font)
        self.single.setObjectName("single")
        self.mode = QtWidgets.QLabel(parent=self.centralwidget)
        self.mode.setGeometry(QtCore.QRect(100, 300, 70, 15))
        font = QtGui.QFont()
        font.setFamily("Comic Sans MS")
        self.mode.setFont(font)
        self.mode.setObjectName("mode")
        self.komi = QtWidgets.QLabel(parent=self.centralwidget)
        self.komi.setGeometry(QtCore.QRect(50, 250, 211, 40))
        font = QtGui.QFont()
        font.setFamily("Comic Sans MS")
        self.komi.setFont(font)
        self.komi.setObjectName("komi")
        self.handi = QtWidgets.QLabel(parent=self.centralwidget)
        self.handi.setGeometry(QtCore.QRect(100, 200, 100, 50))
        font = QtGui.QFont()
        font.setFamily("Comic Sans MS")
        self.handi.setFont(font)
        self.handi.setObjectName("handi")
        self.handiin = QtWidgets.QPlainTextEdit(parent=self.centralwidget)
        self.handiin.setGeometry(QtCore.QRect(325, 210, 100, 25))
        self.handiin.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarPolicy.ScrollBarAlwaysOff)
        self.handiin.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarPolicy.ScrollBarAlwaysOff)
        self.handiin.setObjectName("handiin")
        self.komiin = QtWidgets.QPlainTextEdit(parent=self.centralwidget)
        self.komiin.setGeometry(QtCore.QRect(325, 250, 100, 25))
        self.komiin.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarPolicy.ScrollBarAlwaysOff)
        self.komiin.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarPolicy.ScrollBarAlwaysOff)
        self.komiin.setObjectName("komiin")
        startscr.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(parent=startscr)
        self.statusbar.setObjectName("statusbar")
        startscr.setStatusBar(self.statusbar)

        self.retranslateUi(startscr)
        QtCore.QMetaObject.connectSlotsByName(startscr)

    def retranslateUi(self, startscr):
        _translate = QtCore.QCoreApplication.translate
        startscr.setWindowTitle(_translate("startscr", "MainWindow"))
        self.gamename.setText(_translate("startscr", "GO"))
        self.start.setText(_translate("startscr", "start"))
        self.doub.setText(_translate("startscr", "double click"))
        self.single.setText(_translate("startscr", "single click"))
        self.mode.setText(_translate("startscr", "place mode"))
        self.komi.setText(_translate("startscr", "Komi(extra points to white player)"))
        self.handi.setText(_translate("startscr", "handicap 0-9"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    startscr = QtWidgets.QMainWindow()
    ui = Ui_startscr()
    ui.setupUi(startscr)
    startscr.show()
    sys.exit(app.exec())
